apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: accounts-virtual-host-ingress
spec:
  rules:
  - http:
      paths:
      - path: /accounts
        backend:
          serviceName: accounts-service
          servicePort: 8080