version: 2.1

orbs:
  vexe: virtuaorbs/executors@0.1.0
  vcom: virtuaorbs/commands@0.3.0
  kube: circleci/kubernetes@0.11.0

jobs:
  test-job:
    executor: vexe/mongoruby_2-6-3
    steps:
      - vcom/run-test-suites:
          filename: 'tests'
          suite: 'spec/controllers/accounts_spec.rb'
  doc-job:
    executor: vexe/mongoruby_2-6-3
    steps:
      - vcom/generate-documentation
  rubocop-job:
    docker:
      - image: circleci/ruby-2.6.5-node-browsers
    steps:
      - run: mkdir /tmp/accounts
      - run: |
          bundle update --bundler |
          bundle install
      - run: |
          bundle exec rubocop -F -f h -o /tmp/accounts/results.html controllers/ decorators/ services/
      - store_test_results:
          path: /tmp/accounts
      - store_artifacts:
          path: /tmp/accounts
          destination: accounts
  build-job:
    docker:
      - image: circleci/ruby-2.6.5-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
      - run: |
          gem install virtuatable:2.3.0
      - run: |
          virtuatable docker create accounts
  deploy-job:
    docker:
      - image: circleci/ruby-2.6.5-node-browsers
    steps:
      - kube/install-kubectl
      - kube/install-kubeconfig:
          kubeconfig: KUBECONFIG
      - run: |
          gem install virtuatable:2.3.0
      - run: |
          virtuatable kube create accounts

  restart-job:
    executor: vexe/mongoruby_2-6-3
    steps:
      - vcom/perform-capistrano-command:
          command: "deploy:start"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - test-job:
          requires:
            - rubocop-job
      - doc-job:
          requires:
            - rubocop-job
      - build-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master