development:
  clients:
    default:
      database: arkaan_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: arkaan_test
      hosts:
        - localhost:27017
production:
  clients:
    defaults:
      uri: <%= ENV['MONGODB_URL'] %>